// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TaskManagementSystem.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240406150630_AddNotificationsTable")]
    partial class AddNotificationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Country", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("countryCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("flagSvg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phoneCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("timeZone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("countries");

                    b.HasData(
                        new
                        {
                            id = 100,
                            countryCode = "LY",
                            flagSvg = "https://flagcdn.com/ly.svg",
                            name = "Libya",
                            phoneCode = "+434",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 101,
                            countryCode = "KR",
                            flagSvg = "https://flagcdn.com/kr.svg",
                            name = "South Korea",
                            phoneCode = "+410",
                            timeZone = "UTC+09:00"
                        },
                        new
                        {
                            id = 102,
                            countryCode = "LI",
                            flagSvg = "https://flagcdn.com/li.svg",
                            name = "Liechtenstein",
                            phoneCode = "+438",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 103,
                            countryCode = "NI",
                            flagSvg = "https://flagcdn.com/ni.svg",
                            name = "Nicaragua",
                            phoneCode = "+558",
                            timeZone = "UTC-06:00"
                        },
                        new
                        {
                            id = 104,
                            countryCode = "EC",
                            flagSvg = "https://flagcdn.com/ec.svg",
                            name = "Ecuador",
                            phoneCode = "+218",
                            timeZone = "UTC-06:00"
                        },
                        new
                        {
                            id = 105,
                            countryCode = "MV",
                            flagSvg = "https://flagcdn.com/mv.svg",
                            name = "Maldives",
                            phoneCode = "+462",
                            timeZone = "UTC+05:00"
                        },
                        new
                        {
                            id = 106,
                            countryCode = "DZ",
                            flagSvg = "https://flagcdn.com/dz.svg",
                            name = "Algeria",
                            phoneCode = "+012",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 107,
                            countryCode = "KG",
                            flagSvg = "https://flagcdn.com/kg.svg",
                            name = "Kyrgyzstan",
                            phoneCode = "+417",
                            timeZone = "UTC+06:00"
                        },
                        new
                        {
                            id = 108,
                            countryCode = "FI",
                            flagSvg = "https://flagcdn.com/fi.svg",
                            name = "Finland",
                            phoneCode = "+246",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 109,
                            countryCode = "AQ",
                            flagSvg = "https://flagcdn.com/aq.svg",
                            name = "Antarctica",
                            phoneCode = "+010",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 110,
                            countryCode = "KE",
                            flagSvg = "https://flagcdn.com/ke.svg",
                            name = "Kenya",
                            phoneCode = "+404",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 111,
                            countryCode = "CU",
                            flagSvg = "https://flagcdn.com/cu.svg",
                            name = "Cuba",
                            phoneCode = "+192",
                            timeZone = "UTC-05:00"
                        },
                        new
                        {
                            id = 112,
                            countryCode = "MS",
                            flagSvg = "https://flagcdn.com/ms.svg",
                            name = "Montserrat",
                            phoneCode = "+500",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 113,
                            countryCode = "PL",
                            flagSvg = "https://flagcdn.com/pl.svg",
                            name = "Poland",
                            phoneCode = "+616",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 114,
                            countryCode = "AX",
                            flagSvg = "https://flagcdn.com/ax.svg",
                            name = "Åland Islands",
                            phoneCode = "+248",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 115,
                            countryCode = "ET",
                            flagSvg = "https://flagcdn.com/et.svg",
                            name = "Ethiopia",
                            phoneCode = "+231",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 116,
                            countryCode = "TG",
                            flagSvg = "https://flagcdn.com/tg.svg",
                            name = "Togo",
                            phoneCode = "+768",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 117,
                            countryCode = "BA",
                            flagSvg = "https://flagcdn.com/ba.svg",
                            name = "Bosnia and Herzegovina",
                            phoneCode = "+070",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 118,
                            countryCode = "UY",
                            flagSvg = "https://flagcdn.com/uy.svg",
                            name = "Uruguay",
                            phoneCode = "+858",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 119,
                            countryCode = "GU",
                            flagSvg = "https://flagcdn.com/gu.svg",
                            name = "Guam",
                            phoneCode = "+316",
                            timeZone = "UTC+10:00"
                        },
                        new
                        {
                            id = 120,
                            countryCode = "CV",
                            flagSvg = "https://flagcdn.com/cv.svg",
                            name = "Cape Verde",
                            phoneCode = "+132",
                            timeZone = "UTC-01:00"
                        },
                        new
                        {
                            id = 121,
                            countryCode = "TD",
                            flagSvg = "https://flagcdn.com/td.svg",
                            name = "Chad",
                            phoneCode = "+148",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 122,
                            countryCode = "VA",
                            flagSvg = "https://flagcdn.com/va.svg",
                            name = "Vatican City",
                            phoneCode = "+336",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 123,
                            countryCode = "PW",
                            flagSvg = "https://flagcdn.com/pw.svg",
                            name = "Palau",
                            phoneCode = "+585",
                            timeZone = "UTC+09:00"
                        },
                        new
                        {
                            id = 124,
                            countryCode = "HT",
                            flagSvg = "https://flagcdn.com/ht.svg",
                            name = "Haiti",
                            phoneCode = "+332",
                            timeZone = "UTC-05:00"
                        },
                        new
                        {
                            id = 125,
                            countryCode = "YE",
                            flagSvg = "https://flagcdn.com/ye.svg",
                            name = "Yemen",
                            phoneCode = "+887",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 126,
                            countryCode = "SZ",
                            flagSvg = "https://flagcdn.com/sz.svg",
                            name = "Eswatini",
                            phoneCode = "+748",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 127,
                            countryCode = "ZW",
                            flagSvg = "https://flagcdn.com/zw.svg",
                            name = "Zimbabwe",
                            phoneCode = "+716",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 128,
                            countryCode = "GR",
                            flagSvg = "https://flagcdn.com/gr.svg",
                            name = "Greece",
                            phoneCode = "+300",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 130,
                            countryCode = "MF",
                            flagSvg = "https://flagcdn.com/mf.svg",
                            name = "Saint Martin",
                            phoneCode = "+663",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 131,
                            countryCode = "AG",
                            flagSvg = "https://flagcdn.com/ag.svg",
                            name = "Antigua and Barbuda",
                            phoneCode = "+028",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 132,
                            countryCode = "CY",
                            flagSvg = "https://flagcdn.com/cy.svg",
                            name = "Cyprus",
                            phoneCode = "+196",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 133,
                            countryCode = "SX",
                            flagSvg = "https://flagcdn.com/sx.svg",
                            name = "Sint Maarten",
                            phoneCode = "+534",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 134,
                            countryCode = "MC",
                            flagSvg = "https://flagcdn.com/mc.svg",
                            name = "Monaco",
                            phoneCode = "+492",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 135,
                            countryCode = "FJ",
                            flagSvg = "https://flagcdn.com/fj.svg",
                            name = "Fiji",
                            phoneCode = "+242",
                            timeZone = "UTC+12:00"
                        },
                        new
                        {
                            id = 136,
                            countryCode = "UA",
                            flagSvg = "https://flagcdn.com/ua.svg",
                            name = "Ukraine",
                            phoneCode = "+804",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 137,
                            countryCode = "MQ",
                            flagSvg = "https://flagcdn.com/mq.svg",
                            name = "Martinique",
                            phoneCode = "+474",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 138,
                            countryCode = "HK",
                            flagSvg = "https://flagcdn.com/hk.svg",
                            name = "Hong Kong",
                            phoneCode = "+344",
                            timeZone = "UTC+08:00"
                        },
                        new
                        {
                            id = 139,
                            countryCode = "PT",
                            flagSvg = "https://flagcdn.com/pt.svg",
                            name = "Portugal",
                            phoneCode = "+620",
                            timeZone = "UTC-01:00"
                        },
                        new
                        {
                            id = 140,
                            countryCode = "BT",
                            flagSvg = "https://flagcdn.com/bt.svg",
                            name = "Bhutan",
                            phoneCode = "+064",
                            timeZone = "UTC+06:00"
                        },
                        new
                        {
                            id = 141,
                            countryCode = "NP",
                            flagSvg = "https://flagcdn.com/np.svg",
                            name = "Nepal",
                            phoneCode = "+524",
                            timeZone = "UTC+05:45"
                        },
                        new
                        {
                            id = 142,
                            countryCode = "FR",
                            flagSvg = "https://flagcdn.com/fr.svg",
                            name = "France",
                            phoneCode = "+250",
                            timeZone = "UTC-10:00"
                        },
                        new
                        {
                            id = 143,
                            countryCode = "IE",
                            flagSvg = "https://flagcdn.com/ie.svg",
                            name = "Ireland",
                            phoneCode = "+372",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 144,
                            countryCode = "AE",
                            flagSvg = "https://flagcdn.com/ae.svg",
                            name = "United Arab Emirates",
                            phoneCode = "+784",
                            timeZone = "UTC+04:00"
                        },
                        new
                        {
                            id = 145,
                            countryCode = "GG",
                            flagSvg = "https://flagcdn.com/gg.svg",
                            name = "Guernsey",
                            phoneCode = "+831",
                            timeZone = "UTC+00:00"
                        },
                        new
                        {
                            id = 146,
                            countryCode = "LC",
                            flagSvg = "https://flagcdn.com/lc.svg",
                            name = "Saint Lucia",
                            phoneCode = "+662",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 147,
                            countryCode = "DO",
                            flagSvg = "https://flagcdn.com/do.svg",
                            name = "Dominican Republic",
                            phoneCode = "+214",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 148,
                            countryCode = "RS",
                            flagSvg = "https://flagcdn.com/rs.svg",
                            name = "Serbia",
                            phoneCode = "+688",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 149,
                            countryCode = "BW",
                            flagSvg = "https://flagcdn.com/bw.svg",
                            name = "Botswana",
                            phoneCode = "+072",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 150,
                            countryCode = "CI",
                            flagSvg = "https://flagcdn.com/ci.svg",
                            name = "Ivory Coast",
                            phoneCode = "+384",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 151,
                            countryCode = "GH",
                            flagSvg = "https://flagcdn.com/gh.svg",
                            name = "Ghana",
                            phoneCode = "+288",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 152,
                            countryCode = "KM",
                            flagSvg = "https://flagcdn.com/km.svg",
                            name = "Comoros",
                            phoneCode = "+174",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 153,
                            countryCode = "AZ",
                            flagSvg = "https://flagcdn.com/az.svg",
                            name = "Azerbaijan",
                            phoneCode = "+031",
                            timeZone = "UTC+04:00"
                        },
                        new
                        {
                            id = 154,
                            countryCode = "GB",
                            flagSvg = "https://flagcdn.com/gb.svg",
                            name = "United Kingdom",
                            phoneCode = "+826",
                            timeZone = "UTC-08:00"
                        },
                        new
                        {
                            id = 155,
                            countryCode = "CF",
                            flagSvg = "https://flagcdn.com/cf.svg",
                            name = "Central African Republic",
                            phoneCode = "+140",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 156,
                            countryCode = "PS",
                            flagSvg = "https://flagcdn.com/ps.svg",
                            name = "Palestine",
                            phoneCode = "+275",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 157,
                            countryCode = "BQ",
                            flagSvg = "https://flagcdn.com/bq.svg",
                            name = "Caribbean Netherlands",
                            phoneCode = "+535",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 158,
                            countryCode = "TW",
                            flagSvg = "https://flagcdn.com/tw.svg",
                            name = "Taiwan",
                            phoneCode = "+158",
                            timeZone = "UTC+08:00"
                        },
                        new
                        {
                            id = 159,
                            countryCode = "KI",
                            flagSvg = "https://flagcdn.com/ki.svg",
                            name = "Kiribati",
                            phoneCode = "+296",
                            timeZone = "UTC+12:00"
                        },
                        new
                        {
                            id = 160,
                            countryCode = "VE",
                            flagSvg = "https://flagcdn.com/ve.svg",
                            name = "Venezuela",
                            phoneCode = "+862",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 161,
                            countryCode = "BF",
                            flagSvg = "https://flagcdn.com/bf.svg",
                            name = "Burkina Faso",
                            phoneCode = "+854",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 162,
                            countryCode = "BJ",
                            flagSvg = "https://flagcdn.com/bj.svg",
                            name = "Benin",
                            phoneCode = "+204",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 163,
                            countryCode = "EH",
                            flagSvg = "https://flagcdn.com/eh.svg",
                            name = "Western Sahara",
                            phoneCode = "+732",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 164,
                            countryCode = "FI",
                            flagSvg = "https://flagcdn.com/fi.svg",
                            name = "Finland",
                            phoneCode = "+246",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 165,
                            countryCode = "GI",
                            flagSvg = "https://flagcdn.com/gi.svg",
                            name = "Gibraltar",
                            phoneCode = "+292",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 166,
                            countryCode = "ML",
                            flagSvg = "https://flagcdn.com/ml.svg",
                            name = "Mali",
                            phoneCode = "+466",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 167,
                            countryCode = "AR",
                            flagSvg = "https://flagcdn.com/ar.svg",
                            name = "Argentina",
                            phoneCode = "+032",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 168,
                            countryCode = "SC",
                            flagSvg = "https://flagcdn.com/sc.svg",
                            name = "Seychelles",
                            phoneCode = "+690",
                            timeZone = "UTC+04:00"
                        },
                        new
                        {
                            id = 169,
                            countryCode = "MD",
                            flagSvg = "https://flagcdn.com/md.svg",
                            name = "Moldova",
                            phoneCode = "+498",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 170,
                            countryCode = "NR",
                            flagSvg = "https://flagcdn.com/nr.svg",
                            name = "Nauru",
                            phoneCode = "+520",
                            timeZone = "UTC+12:00"
                        },
                        new
                        {
                            id = 171,
                            countryCode = "IT",
                            flagSvg = "https://flagcdn.com/it.svg",
                            name = "Italy",
                            phoneCode = "+380",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 172,
                            countryCode = "VU",
                            flagSvg = "https://flagcdn.com/vu.svg",
                            name = "Vanuatu",
                            phoneCode = "+548",
                            timeZone = "UTC+11:00"
                        },
                        new
                        {
                            id = 173,
                            countryCode = "PW",
                            flagSvg = "https://flagcdn.com/pw.svg",
                            name = "Palau",
                            phoneCode = "+585",
                            timeZone = "UTC+09:00"
                        },
                        new
                        {
                            id = 174,
                            countryCode = "UZ",
                            flagSvg = "https://flagcdn.com/uz.svg",
                            name = "Uzbekistan",
                            phoneCode = "+860",
                            timeZone = "UTC+05:00"
                        },
                        new
                        {
                            id = 175,
                            countryCode = "CG",
                            flagSvg = "https://flagcdn.com/cg.svg",
                            name = "Congo",
                            phoneCode = "+178",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 176,
                            countryCode = "TC",
                            flagSvg = "https://flagcdn.com/tc.svg",
                            name = "Turks and Caicos Islands",
                            phoneCode = "+796",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 177,
                            countryCode = "CL",
                            flagSvg = "https://flagcdn.com/cl.svg",
                            name = "Chile",
                            phoneCode = "+152",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 178,
                            countryCode = "MA",
                            flagSvg = "https://flagcdn.com/ma.svg",
                            name = "Morocco",
                            phoneCode = "+504",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 179,
                            countryCode = "CH",
                            flagSvg = "https://flagcdn.com/ch.svg",
                            name = "Switzerland",
                            phoneCode = "+756",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 180,
                            countryCode = "DK",
                            flagSvg = "https://flagcdn.com/dk.svg",
                            name = "Denmark",
                            phoneCode = "+208",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 181,
                            countryCode = "SH",
                            flagSvg = "https://flagcdn.com/sh.svg",
                            name = "Saint Helena",
                            phoneCode = "+654",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 182,
                            countryCode = "NI",
                            flagSvg = "https://flagcdn.com/ni.svg",
                            name = "Nicaragua",
                            phoneCode = "+558",
                            timeZone = "UTC-06:00"
                        },
                        new
                        {
                            id = 183,
                            countryCode = "BB",
                            flagSvg = "https://flagcdn.com/bb.svg",
                            name = "Barbados",
                            phoneCode = "+052",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 184,
                            countryCode = "SS",
                            flagSvg = "https://flagcdn.com/ss.svg",
                            name = "South Sudan",
                            phoneCode = "+728",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 185,
                            countryCode = "GL",
                            flagSvg = "https://flagcdn.com/gl.svg",
                            name = "Greenland",
                            phoneCode = "+304",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 186,
                            countryCode = "AW",
                            flagSvg = "https://flagcdn.com/aw.svg",
                            name = "Aruba",
                            phoneCode = "+533",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 187,
                            countryCode = "OM",
                            flagSvg = "https://flagcdn.com/om.svg",
                            name = "Oman",
                            phoneCode = "+512",
                            timeZone = "UTC+04:00"
                        },
                        new
                        {
                            id = 188,
                            countryCode = "ER",
                            flagSvg = "https://flagcdn.com/er.svg",
                            name = "Eritrea",
                            phoneCode = "+232",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 189,
                            countryCode = "XK",
                            flagSvg = "https://flagcdn.com/xk.svg",
                            name = "Kosovo",
                            phoneCode = "+780",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 190,
                            countryCode = "SK",
                            flagSvg = "https://flagcdn.com/sk.svg",
                            name = "Slovakia",
                            phoneCode = "+703",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 191,
                            countryCode = "DZ",
                            flagSvg = "https://flagcdn.com/dz.svg",
                            name = "Algeria",
                            phoneCode = "+012",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 192,
                            countryCode = "PE",
                            flagSvg = "https://flagcdn.com/pe.svg",
                            name = "Peru",
                            phoneCode = "+604",
                            timeZone = "UTC-05:00"
                        },
                        new
                        {
                            id = 193,
                            countryCode = "SR",
                            flagSvg = "https://flagcdn.com/sr.svg",
                            name = "Suriname",
                            phoneCode = "+740",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 194,
                            countryCode = "RO",
                            flagSvg = "https://flagcdn.com/ro.svg",
                            name = "Romania",
                            phoneCode = "+642",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 195,
                            countryCode = "BE",
                            flagSvg = "https://flagcdn.com/be.svg",
                            name = "Belgium",
                            phoneCode = "+056",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 196,
                            countryCode = "SZ",
                            flagSvg = "https://flagcdn.com/sz.svg",
                            name = "Swaziland",
                            phoneCode = "+748",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 197,
                            countryCode = "SY",
                            flagSvg = "https://flagcdn.com/sy.svg",
                            name = "Syria",
                            phoneCode = "+760",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 198,
                            countryCode = "US",
                            flagSvg = "https://flagcdn.com/us.svg",
                            name = "United States",
                            phoneCode = "+840",
                            timeZone = "UTC-12:00"
                        },
                        new
                        {
                            id = 199,
                            countryCode = "TG",
                            flagSvg = "https://flagcdn.com/tg.svg",
                            name = "Togo",
                            phoneCode = "+768",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 200,
                            countryCode = "LR",
                            flagSvg = "https://flagcdn.com/lr.svg",
                            name = "Liberia",
                            phoneCode = "+430",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 201,
                            countryCode = "BH",
                            flagSvg = "https://flagcdn.com/bh.svg",
                            name = "Bahrain",
                            phoneCode = "+048",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 202,
                            countryCode = "SG",
                            flagSvg = "https://flagcdn.com/sg.svg",
                            name = "Singapore",
                            phoneCode = "+702",
                            timeZone = "UTC+08:00"
                        },
                        new
                        {
                            id = 203,
                            countryCode = "SI",
                            flagSvg = "https://flagcdn.com/si.svg",
                            name = "Slovenia",
                            phoneCode = "+705",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 204,
                            countryCode = "KN",
                            flagSvg = "https://flagcdn.com/kn.svg",
                            name = "Saint Kitts and Nevis",
                            phoneCode = "+659",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 205,
                            countryCode = "BI",
                            flagSvg = "https://flagcdn.com/bi.svg",
                            name = "Burundi",
                            phoneCode = "+108",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 206,
                            countryCode = "PM",
                            flagSvg = "https://flagcdn.com/pm.svg",
                            name = "Saint Pierre and Miquelon",
                            phoneCode = "+666",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 207,
                            countryCode = "MH",
                            flagSvg = "https://flagcdn.com/mh.svg",
                            name = "Marshall Islands",
                            phoneCode = "+584",
                            timeZone = "UTC+12:00"
                        },
                        new
                        {
                            id = 208,
                            countryCode = "TV",
                            flagSvg = "https://flagcdn.com/tv.svg",
                            name = "Tuvalu",
                            phoneCode = "+798",
                            timeZone = "UTC+12:00"
                        },
                        new
                        {
                            id = 209,
                            countryCode = "TZ",
                            flagSvg = "https://flagcdn.com/tz.svg",
                            name = "Tanzania",
                            phoneCode = "+834",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 210,
                            countryCode = "YE",
                            flagSvg = "https://flagcdn.com/ye.svg",
                            name = "Yemen",
                            phoneCode = "+887",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 211,
                            countryCode = "ME",
                            flagSvg = "https://flagcdn.com/me.svg",
                            name = "Montenegro",
                            phoneCode = "+499",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 212,
                            countryCode = "NF",
                            flagSvg = "https://flagcdn.com/nf.svg",
                            name = "Norfolk Island",
                            phoneCode = "+574",
                            timeZone = "UTC+11:30"
                        },
                        new
                        {
                            id = 213,
                            countryCode = "MW",
                            flagSvg = "https://flagcdn.com/mw.svg",
                            name = "Malawi",
                            phoneCode = "+454",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 214,
                            countryCode = "ZW",
                            flagSvg = "https://flagcdn.com/zw.svg",
                            name = "Zimbabwe",
                            phoneCode = "+716",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 215,
                            countryCode = "JO",
                            flagSvg = "https://flagcdn.com/jo.svg",
                            name = "Jordan",
                            phoneCode = "+400",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 216,
                            countryCode = "CA",
                            flagSvg = "https://flagcdn.com/ca.svg",
                            name = "Canada",
                            phoneCode = "+124",
                            timeZone = "UTC-08:00"
                        },
                        new
                        {
                            id = 217,
                            countryCode = "SJ",
                            flagSvg = "https://flagcdn.com/sj.svg",
                            name = "Svalbard and Jan Mayen",
                            phoneCode = "+744",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 218,
                            countryCode = "SB",
                            flagSvg = "https://flagcdn.com/sb.svg",
                            name = "Solomon Islands",
                            phoneCode = "+090",
                            timeZone = "UTC+11:00"
                        },
                        new
                        {
                            id = 219,
                            countryCode = "CK",
                            flagSvg = "https://flagcdn.com/ck.svg",
                            name = "Cook Islands",
                            phoneCode = "+184",
                            timeZone = "UTC-10:00"
                        },
                        new
                        {
                            id = 220,
                            countryCode = "BD",
                            flagSvg = "https://flagcdn.com/bd.svg",
                            name = "Bangladesh",
                            phoneCode = "+050",
                            timeZone = "UTC+06:00"
                        },
                        new
                        {
                            id = 221,
                            countryCode = "ID",
                            flagSvg = "https://flagcdn.com/id.svg",
                            name = "Indonesia",
                            phoneCode = "+360",
                            timeZone = "UTC+09:00"
                        },
                        new
                        {
                            id = 222,
                            countryCode = "FK",
                            flagSvg = "https://flagcdn.com/fk.svg",
                            name = "Falkland Islands",
                            phoneCode = "+238",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 223,
                            countryCode = "DM",
                            flagSvg = "https://flagcdn.com/dm.svg",
                            name = "Dominica",
                            phoneCode = "+212",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 224,
                            countryCode = "MM",
                            flagSvg = "https://flagcdn.com/mm.svg",
                            name = "Myanmar",
                            phoneCode = "+104",
                            timeZone = "UTC+06:30"
                        },
                        new
                        {
                            id = 225,
                            countryCode = "AO",
                            flagSvg = "https://flagcdn.com/ao.svg",
                            name = "Angola",
                            phoneCode = "+024",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 226,
                            countryCode = "TK",
                            flagSvg = "https://flagcdn.com/tk.svg",
                            name = "Tokelau",
                            phoneCode = "+772",
                            timeZone = "UTC+14:00"
                        },
                        new
                        {
                            id = 227,
                            countryCode = "KH",
                            flagSvg = "https://flagcdn.com/kh.svg",
                            name = "Cambodia",
                            phoneCode = "+116",
                            timeZone = "UTC+07:00"
                        },
                        new
                        {
                            id = 228,
                            countryCode = "AU",
                            flagSvg = "https://flagcdn.com/au.svg",
                            name = "Australia",
                            phoneCode = "+036",
                            timeZone = "UTC+11:00"
                        },
                        new
                        {
                            id = 229,
                            countryCode = "BZ",
                            flagSvg = "https://flagcdn.com/bz.svg",
                            name = "Belize",
                            phoneCode = "+084",
                            timeZone = "UTC-06:00"
                        },
                        new
                        {
                            id = 230,
                            countryCode = "MN",
                            flagSvg = "https://flagcdn.com/mn.svg",
                            name = "Mongolia",
                            phoneCode = "+496",
                            timeZone = "UTC+08:00"
                        },
                        new
                        {
                            id = 231,
                            countryCode = "GT",
                            flagSvg = "https://flagcdn.com/gt.svg",
                            name = "Guatemala",
                            phoneCode = "+320",
                            timeZone = "UTC-06:00"
                        },
                        new
                        {
                            id = 232,
                            countryCode = "EG",
                            flagSvg = "https://flagcdn.com/eg.svg",
                            name = "Egypt",
                            phoneCode = "+818",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 233,
                            countryCode = "EC",
                            flagSvg = "https://flagcdn.com/ec.svg",
                            name = "Ecuador",
                            phoneCode = "+218",
                            timeZone = "UTC-06:00"
                        },
                        new
                        {
                            id = 234,
                            countryCode = "BL",
                            flagSvg = "https://flagcdn.com/bl.svg",
                            name = "Saint Barthélemy",
                            phoneCode = "+652",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 235,
                            countryCode = "PN",
                            flagSvg = "https://flagcdn.com/pn.svg",
                            name = "Pitcairn",
                            phoneCode = "+612",
                            timeZone = "UTC-08:00"
                        },
                        new
                        {
                            id = 236,
                            countryCode = "NO",
                            flagSvg = "https://flagcdn.com/no.svg",
                            name = "Norway",
                            phoneCode = "+578",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 237,
                            countryCode = "VC",
                            flagSvg = "https://flagcdn.com/vc.svg",
                            name = "Saint Vincent and the Grenadines",
                            phoneCode = "+670",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 238,
                            countryCode = "NZ",
                            flagSvg = "https://flagcdn.com/nz.svg",
                            name = "New Zealand",
                            phoneCode = "+554",
                            timeZone = "UTC+13:00"
                        },
                        new
                        {
                            id = 239,
                            countryCode = "GA",
                            flagSvg = "https://flagcdn.com/ga.svg",
                            name = "Gabon",
                            phoneCode = "+266",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 240,
                            countryCode = "PG",
                            flagSvg = "https://flagcdn.com/pg.svg",
                            name = "Papua New Guinea",
                            phoneCode = "+598",
                            timeZone = "UTC+10:00"
                        },
                        new
                        {
                            id = 241,
                            countryCode = "CV",
                            flagSvg = "https://flagcdn.com/cv.svg",
                            name = "Cape Verde",
                            phoneCode = "+132",
                            timeZone = "UTC-01:00"
                        },
                        new
                        {
                            id = 242,
                            countryCode = "IN",
                            flagSvg = "https://flagcdn.com/in.svg",
                            name = "India",
                            phoneCode = "+356",
                            timeZone = "UTC+05:30"
                        },
                        new
                        {
                            id = 243,
                            countryCode = "HT",
                            flagSvg = "https://flagcdn.com/ht.svg",
                            name = "Haiti",
                            phoneCode = "+332",
                            timeZone = "UTC-05:00"
                        },
                        new
                        {
                            id = 244,
                            countryCode = "GM",
                            flagSvg = "https://flagcdn.com/gm.svg",
                            name = "Gambia",
                            phoneCode = "+270",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 245,
                            countryCode = "AL",
                            flagSvg = "https://flagcdn.com/al.svg",
                            name = "Albania",
                            phoneCode = "+008",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 246,
                            countryCode = "SE",
                            flagSvg = "https://flagcdn.com/se.svg",
                            name = "Sweden",
                            phoneCode = "+752",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 247,
                            countryCode = "CY",
                            flagSvg = "https://flagcdn.com/cy.svg",
                            name = "Cyprus",
                            phoneCode = "+196",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 248,
                            countryCode = "MU",
                            flagSvg = "https://flagcdn.com/mu.svg",
                            name = "Mauritius",
                            phoneCode = "+480",
                            timeZone = "UTC+04:00"
                        },
                        new
                        {
                            id = 249,
                            countryCode = "VN",
                            flagSvg = "https://flagcdn.com/vn.svg",
                            name = "Vietnam",
                            phoneCode = "+704",
                            timeZone = "UTC+07:00"
                        },
                        new
                        {
                            id = 250,
                            countryCode = "MA",
                            flagSvg = "https://flagcdn.com/ma.svg",
                            name = "Morocco",
                            phoneCode = "+504",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 251,
                            countryCode = "TJ",
                            flagSvg = "https://flagcdn.com/tj.svg",
                            name = "Tajikistan",
                            phoneCode = "+762",
                            timeZone = "UTC+05:00"
                        },
                        new
                        {
                            id = 252,
                            countryCode = "LB",
                            flagSvg = "https://flagcdn.com/lb.svg",
                            name = "Lebanon",
                            phoneCode = "+961",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 253,
                            countryCode = "BM",
                            flagSvg = "https://flagcdn.com/bm.svg",
                            name = "Bermuda",
                            phoneCode = "+060",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 254,
                            countryCode = "NL",
                            flagSvg = "https://flagcdn.com/nl.svg",
                            name = "Netherlands",
                            phoneCode = "+528",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 255,
                            countryCode = "SA",
                            flagSvg = "https://flagcdn.com/sa.svg",
                            name = "Saudi Arabia",
                            phoneCode = "+682",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 256,
                            countryCode = "DE",
                            flagSvg = "https://flagcdn.com/de.svg",
                            name = "Germany",
                            phoneCode = "+276",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 257,
                            countryCode = "GW",
                            flagSvg = "https://flagcdn.com/gw.svg",
                            name = "Guinea-Bissau",
                            phoneCode = "+624",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 258,
                            countryCode = "RU",
                            flagSvg = "https://flagcdn.com/ru.svg",
                            name = "Russia",
                            phoneCode = "+643",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 259,
                            countryCode = "SN",
                            flagSvg = "https://flagcdn.com/sn.svg",
                            name = "Senegal",
                            phoneCode = "+686",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 260,
                            countryCode = "MY",
                            flagSvg = "https://flagcdn.com/my.svg",
                            name = "Malaysia",
                            phoneCode = "+458",
                            timeZone = "UTC+08:00"
                        },
                        new
                        {
                            id = 261,
                            countryCode = "IR",
                            flagSvg = "https://flagcdn.com/ir.svg",
                            name = "Iran",
                            phoneCode = "+364",
                            timeZone = "UTC+03:30"
                        },
                        new
                        {
                            id = 262,
                            countryCode = "LK",
                            flagSvg = "https://flagcdn.com/lk.svg",
                            name = "Sri Lanka",
                            phoneCode = "+144",
                            timeZone = "UTC+05:30"
                        },
                        new
                        {
                            id = 263,
                            countryCode = "AI",
                            flagSvg = "https://flagcdn.com/ai.svg",
                            name = "Anguilla",
                            phoneCode = "+660",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 264,
                            countryCode = "IO",
                            flagSvg = "https://flagcdn.com/io.svg",
                            name = "British Indian Ocean Territory",
                            phoneCode = "+086",
                            timeZone = "UTC+06:00"
                        },
                        new
                        {
                            id = 265,
                            countryCode = "RS",
                            flagSvg = "https://flagcdn.com/rs.svg",
                            name = "Serbia",
                            phoneCode = "+688",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 266,
                            countryCode = "LU",
                            flagSvg = "https://flagcdn.com/lu.svg",
                            name = "Luxembourg",
                            phoneCode = "+442",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 267,
                            countryCode = "TR",
                            flagSvg = "https://flagcdn.com/tr.svg",
                            name = "Turkey",
                            phoneCode = "+792",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 268,
                            countryCode = "BY",
                            flagSvg = "https://flagcdn.com/by.svg",
                            name = "Belarus",
                            phoneCode = "+112",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 269,
                            countryCode = "KR",
                            flagSvg = "https://flagcdn.com/kr.svg",
                            name = "South Korea",
                            phoneCode = "+410",
                            timeZone = "UTC+09:00"
                        },
                        new
                        {
                            id = 270,
                            countryCode = "LV",
                            flagSvg = "https://flagcdn.com/lv.svg",
                            name = "Latvia",
                            phoneCode = "+428",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 271,
                            countryCode = "NF",
                            flagSvg = "https://flagcdn.com/nf.svg",
                            name = "Norfolk Island",
                            phoneCode = "+574",
                            timeZone = "UTC+11:30"
                        },
                        new
                        {
                            id = 272,
                            countryCode = "AR",
                            flagSvg = "https://flagcdn.com/ar.svg",
                            name = "Argentina",
                            phoneCode = "+032",
                            timeZone = "UTC-03:00"
                        },
                        new
                        {
                            id = 273,
                            countryCode = "SI",
                            flagSvg = "https://flagcdn.com/si.svg",
                            name = "Slovenia",
                            phoneCode = "+705",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 274,
                            countryCode = "ZM",
                            flagSvg = "https://flagcdn.com/zm.svg",
                            name = "Zambia",
                            phoneCode = "+894",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 275,
                            countryCode = "LY",
                            flagSvg = "https://flagcdn.com/ly.svg",
                            name = "Libya",
                            phoneCode = "+434",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 276,
                            countryCode = "UA",
                            flagSvg = "https://flagcdn.com/ua.svg",
                            name = "Ukraine",
                            phoneCode = "+804",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 277,
                            countryCode = "MD",
                            flagSvg = "https://flagcdn.com/md.svg",
                            name = "Moldova",
                            phoneCode = "+498",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 278,
                            countryCode = "FO",
                            flagSvg = "https://flagcdn.com/fo.svg",
                            name = "Faroe Islands",
                            phoneCode = "+234",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 279,
                            countryCode = "FI",
                            flagSvg = "https://flagcdn.com/fi.svg",
                            name = "Finland",
                            phoneCode = "+246",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 280,
                            countryCode = "MZ",
                            flagSvg = "https://flagcdn.com/mz.svg",
                            name = "Mozambique",
                            phoneCode = "+508",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 281,
                            countryCode = "CZ",
                            flagSvg = "https://flagcdn.com/cz.svg",
                            name = "Czech Republic",
                            phoneCode = "+203",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 282,
                            countryCode = "BA",
                            flagSvg = "https://flagcdn.com/ba.svg",
                            name = "Bosnia and Herzegovina",
                            phoneCode = "+070",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 283,
                            countryCode = "GN",
                            flagSvg = "https://flagcdn.com/gn.svg",
                            name = "Guinea",
                            phoneCode = "+324",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 284,
                            countryCode = "TH",
                            flagSvg = "https://flagcdn.com/th.svg",
                            name = "Thailand",
                            phoneCode = "+764",
                            timeZone = "UTC+07:00"
                        },
                        new
                        {
                            id = 285,
                            countryCode = "SL",
                            flagSvg = "https://flagcdn.com/sl.svg",
                            name = "Sierra Leone",
                            phoneCode = "+694",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 286,
                            countryCode = "MK",
                            flagSvg = "https://flagcdn.com/mk.svg",
                            name = "Macedonia",
                            phoneCode = "+807",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 287,
                            countryCode = "FJ",
                            flagSvg = "https://flagcdn.com/fj.svg",
                            name = "Fiji",
                            phoneCode = "+242",
                            timeZone = "UTC+12:00"
                        },
                        new
                        {
                            id = 288,
                            countryCode = "NG",
                            flagSvg = "https://flagcdn.com/ng.svg",
                            name = "Nigeria",
                            phoneCode = "+566",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 289,
                            countryCode = "FR",
                            flagSvg = "https://flagcdn.com/fr.svg",
                            name = "France",
                            phoneCode = "+250",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 290,
                            countryCode = "PT",
                            flagSvg = "https://flagcdn.com/pt.svg",
                            name = "Portugal",
                            phoneCode = "+620",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 291,
                            countryCode = "BG",
                            flagSvg = "https://flagcdn.com/bg.svg",
                            name = "Bulgaria",
                            phoneCode = "+100",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 292,
                            countryCode = "GR",
                            flagSvg = "https://flagcdn.com/gr.svg",
                            name = "Greece",
                            phoneCode = "+300",
                            timeZone = "UTC+02:00"
                        },
                        new
                        {
                            id = 293,
                            countryCode = "ET",
                            flagSvg = "https://flagcdn.com/et.svg",
                            name = "Ethiopia",
                            phoneCode = "+231",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 294,
                            countryCode = "SH",
                            flagSvg = "https://flagcdn.com/sh.svg",
                            name = "Saint Helena",
                            phoneCode = "+654",
                            timeZone = "UTC"
                        },
                        new
                        {
                            id = 295,
                            countryCode = "GP",
                            flagSvg = "https://flagcdn.com/gp.svg",
                            name = "Guadeloupe",
                            phoneCode = "+312",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 296,
                            countryCode = "UG",
                            flagSvg = "https://flagcdn.com/ug.svg",
                            name = "Uganda",
                            phoneCode = "+800",
                            timeZone = "UTC+03:00"
                        },
                        new
                        {
                            id = 297,
                            countryCode = "MS",
                            flagSvg = "https://flagcdn.com/ms.svg",
                            name = "Montserrat",
                            phoneCode = "+500",
                            timeZone = "UTC-04:00"
                        },
                        new
                        {
                            id = 298,
                            countryCode = "NA",
                            flagSvg = "https://flagcdn.com/na.svg",
                            name = "Namibia",
                            phoneCode = "+516",
                            timeZone = "UTC+01:00"
                        },
                        new
                        {
                            id = 299,
                            countryCode = "TM",
                            flagSvg = "https://flagcdn.com/tm.svg",
                            name = "Turkmenistan",
                            phoneCode = "+795",
                            timeZone = "UTC+05:00"
                        },
                        new
                        {
                            id = 300,
                            countryCode = "IS",
                            flagSvg = "https://flagcdn.com/is.svg",
                            name = "Iceland",
                            phoneCode = "+352",
                            timeZone = "UTC"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Data.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("UserId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Data.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Models.Notification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("forAll")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("userReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("userSenderId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Models.Permission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Models.UserVerificationCode", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "VerificationCode");

                    b.ToTable("UserVerificationCodes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Data.ApplicationRole", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Data.ApplicationUser", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TaskManagementSystem.Server.Models.UserVerificationCode", b =>
                {
                    b.HasOne("TaskManagementSystem.Server.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
